"""Added bugdet to user

Revision ID: f13f6ff6a0ef
Revises: 6097470d5ac1
Create Date: 2024-09-16 12:24:26.972747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13f6ff6a0ef'
down_revision = '6097470d5ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=False, server_default="1500"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
